Bugfix while building sentry as a static library
ld: libsentry.a(sentry_ratelimiter.c.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
librt.so.1: error adding symbols: DSO missing from command line